name: pre-deploy (linters)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'ai_planner/**'
  
jobs:
  pylint:
    name: check code style with pylint
    uses: ahnazary/actions-library/.github/workflows/pylint.yaml@main
  
  black:
    name: check code style with black
    uses: ahnazary/actions-library/.github/workflows/black.yaml@main

  isort:
    name: check code style with isort
    uses: ahnazary/actions-library/.github/workflows/isort.yaml@main

  ruff:
    name: check code style with ruff
    uses: ahnazary/actions-library/.github/workflows/ruff.yaml@main